### PR TITLE
general: cleanup

### PR DESCRIPTION
**Pull request by tupakkatapa**

### CODE REVIEW

**Review by jhvst — APPROVED** [review]
looks fine, remember to nsq

**Comment by tupakkatapa** [comment]
There is nothing to nsq here, lol

**Comment by jhvst** [comment]
Do the bootloader changes not affect the derivation?

**Comment by tupakkatapa** [comment]
We are at nixobolus repository, `nsq` only exists in homestaking-infra. 

EDIT: You probably meant that anyway.

**Comment by tupakkatapa** [comment]
This (https://github.com/ponkila/homestaking-infra/pull/69) was merged after this one if you would like to check the nsq.

**Pull request merged**
