### PR TITLE
modules: sys2x-gc

### PR DESCRIPTION
**Pull request by tupakkatapa**
Added a disk space based automatic garbage collection to the modules to be used wherever.

This could be removed from `ponkila/homestaking-infra/modules` and imported from here.

Module is made by https://github.com/2xsaiko

### CODE REVIEW

**Comment by tupakkatapa** [comment]
@2xsaiko 

I can't find this in your repository. Is there a reason you would have removed it?

**Comment by dblsaiko** [comment]
It's still there: https://git.sr.ht/~dblsaiko/nix-extras/tree/master/item/common/modules/sys2x/gc.nix

**Comment by dblsaiko** [comment]
Ah, right, I moved it from my configuration repo to nix-extras which is the stuff that is explicitly for other people to use.

**Comment by tupakkatapa** [comment]
Sure, my bad. I would have found it if I had looked for it a bit longer. Consider making a repository dedicated to this module, it's pretty handy.

**Comment by dblsaiko** [comment]
That's exactly why I split off nix-extras from my configuration, it has more handy stuff like that such as [a module](https://git.sr.ht/~dblsaiko/nix-extras/tree/master/item/common/modules/sys2x/system-nix.nix) to set up NIX_PATH and the nix registry from flake inputs, which can also pass overlays from your configuration to pinned nixpkgs. 

And of course none of the modules in there do anything unless enabled, so you can just add the main module from the flake output to your configuration which pulls in everything, or just the one you want I suppose.

**Comment by tupakkatapa** [comment]
Oh, I see. In that case, it is much better practice to import it directly from your `nix-extras` flake, now that you have separated them. And if I recall correctly, it wasn't "served" as nixosModule before this change.

Therefore, I am closing this PR. Thanks, Marco.

**Pull request closed without merging**
